remote_theme: StowarzyszenieSamopal/agency-jekyll-theme

url: https://samopal.pl/Hania.github.io/
baseurl: /Hania.github.io/

# Site settings
title: Time 4 Adventure
email: firmowa@poczta.com
description: "Organizujemy super wycieczki. Uczymy jezdzic na nartach i deskach. Nasi instruktorzy są super"


# Team names, titles and social links
people:
- name: Aga
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Bartek
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Hania
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/t4a
  - title: youtube 
    url: http://youtube/urzytkownicy/t4a

# Postal address (add as many lines as necessary)
address:
  - line: T4A Sp. zoo
  - line: ul. Stawowa 34
  - line: 99-999 Wrocław

# Build settings
markdown: kramdown
permalink: pretty
